### ISSUE TITLE
Issue when creating a video

### ISSUE THREAD

**Issue by benjaminsabella** [sebheron/TikTok-Reddit-Text-To-Speech#3]
C:\Users\Administrator\Music>TTSGen.exe -url https://www.reddit.com/r/tifu/comme
nts/v1qkbx/tifu_by_pointing_out_the_groundhog_that_lives_in/ -background subway.
mp4
Unhandled exception. System.Exception: Reddit Video Generator error. See inner e
xception for details.
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array
.
   at RedditTextToSpeech.Logic.RedditVideoGenerator.GenerateVideo(String url, St
ring backgroundVideo, String output, Gender gender, TimeSpan startTime)
   --- End of inner exception stack trace ---
   at RedditTextToSpeech.Logic.RedditVideoGenerator.GenerateVideo(String url, St
ring backgroundVideo, String output, Gender gender, TimeSpan startTime) in C:\Us
ers\Sebhe\Documents\GitHub\TikTok-Reddit-Text-To-Speech\RedditTextToSpeech.Logic
\RedditVideoGenerator.cs:line 92
   at Program.<Main>$(String[] args) in C:\Users\Sebhe\Documents\GitHub\TikTok-R
eddit-Text-To-Speech\RedditTextToSpeech.Presentation\Program.cs:line 52
   at Program.<Main>(String[] args)

C:\Users\Administrator\Music>

# System information
* Windows 2012 server
* 2 GB Ram
* crappy cpu

**Comment by sebheron** [comment]
Any chance you could try the latest update? Some changes have bee made/bugs have been fixed and there's a new release.

**Comment by benjaminsabella** [comment]
Im using the compiled executable

**Comment by benjaminsabella** [comment]
Ill try it out and keep you posted
