### ISSUE TITLE
Tool does not delete temp files

### ISSUE THREAD

**Issue by noahesbjerg** [sebheron/TikTok-Reddit-Text-To-Speech#4]
Hi again,
I noticed that your tool doesn't seem to delete the temp files that it creates in the user directory. Is it possible that you could add, so that it does that?
Example: 
![image](https://user-images.githubusercontent.com/36516229/172004456-b29498db-a2a3-4bd6-9014-50389f481ff9.png)

**Comment by sebheron** [comment]
So these files should be deleted after the video is produced. Where are these files being stored? Are they in the bin folder or are they in the same directory where the video is produced?

**Comment by noahesbjerg** [comment]
> So these files should be deleted after the video is produced. Where are these files being stored? Are they in the bin folder or are they in the same directory where the video is produced?

The files are being made in my user directory.

**Comment by sebheron** [comment]
Okay so I tested it a bit this afternoon and the files do delete when everything succeeds, although its temperamental. I'll probably switch to temporary file storage at some point anyways. For now there's a new branch, that I won't merge in, but it has a method for cleaning out the existing temp files.

Just run `-clean true` and it should clean out the directory.

**Comment by noahesbjerg** [comment]
> Okay so I tested it a bit this afternoon and the files do delete when everything succeeds, although its temperamental. I'll probably switch to temporary file storage at some point anyways. For now there's a new branch, that I won't merge in, but it has a method for cleaning out the existing temp files.
> 
> Just run `-clean true` and it should clean out the directory.

Sorry for the late reply. That fixed it.
